"""Board registry: discovers board groupings from wirelist (.wl) files and DRW metadata.

The primary source of truth for board-to-page mappings is the wirelist files
generated by the SUDS WL (wirelister) tool. These files explicitly list which
DRW schematic pages compose each board. DRW files not covered by any wirelist
fall back to metadata-based grouping using trailer titles.
"""
import os
import glob
import re
from dataclasses import dataclass, field
from collections import defaultdict
from datetime import datetime
import logging

from src.drw_parser import parse_drw_file

logger = logging.getLogger(__name__)

# Known library/utility files to exclude from board groupings
EXCLUDED_FILES = {
    'lib', 'lib1', 'libold', 'libs', 'ecllib', 'nlib', 'tnlib', 'nlibt',
    'libpal', 'pwclib', 'dips', 'foo', 'old', 'micro', '5380', 'el2003'
}

# Wirelists that are binary/corrupt (not text page lists)
EXCLUDED_WIRELISTS = {'eth', 'g', 'p', 'sc1', 'vmemb'}

# Wirelists that are older revisions of another wirelist 
# (map: old_name -> canonical_name it duplicates)
VERSIONED_WIRELISTS = {
    'a0518': 'a', 'a0621': 'a', 'a1': 'a', 'aold': 'a', 'all': 'a',
    'q9': 'q',
    'fold': 'f',
    'x10': 'x',   # subset of x
}


@dataclass
class BoardPage:
    """A single schematic page within a board."""
    name: str           # DRW filename without extension
    filepath: str       # Full path to .drw.O file
    page_num: str       # Page number from trailer (e.g., '1', '8A')
    page_of: str        # Total pages from trailer (e.g., '19')
    title: str          # title_line_1 from trailer
    subtitle: str       # title_line_2 from trailer
    bodies: int         # Number of body placements
    points: int         # Number of connection points
    body_defs: int      # Number of inline body definitions


@dataclass  
class Board:
    """A complete board (set of related schematic pages)."""
    board_id: str       # Slug identifier (e.g., 'q_board')
    name: str           # Human-readable name (e.g., 'Q Board — Sun-2 68010 CPU')
    pages: list[BoardPage] = field(default_factory=list)
    source: str = ''    # 'wirelist' or 'metadata' — how this board was discovered
    wirelist: str = ''  # Name of source wirelist file, if any
    
    @property
    def page_count(self) -> int:
        return len(self.pages)


def slugify(name: str) -> str:
    """Convert board name to filesystem-safe slug."""
    name = name.lower()
    name = re.sub(r'[^a-z0-9]+', '_', name)
    return name.strip('_')


def _parse_wirelists(wl_dir: str) -> dict[str, dict]:
    """Parse all wirelist (.wl) files to extract board-to-page mappings.
    
    Returns dict mapping wirelist_name -> {
        'pages': [page_name, ...],  # e.g., ['Q1', 'Q2', ..., 'Q9']
        'title': str,               # Board title from first page header
        'subtitle': str,            # Board subtitle
        'date': str,                # Wirelist generation date
        'sheet_info': str,          # e.g., 'SHEET 1 OF 9'
    }
    """
    results = {}
    wl_files = sorted(glob.glob(os.path.join(wl_dir, '*.wl')))
    
    for wl_path in wl_files:
        wl_name = os.path.basename(wl_path).replace('.wl', '')
        
        if wl_name in EXCLUDED_WIRELISTS:
            continue
        if wl_name in VERSIONED_WIRELISTS:
            continue
            
        try:
            with open(wl_path, 'r', errors='replace') as f:
                content = f.read()
        except Exception:
            continue
        
        pages = []
        title = ''
        subtitle = ''
        date_str = ''
        
        lines = content.split('\n')
        i = 0
        # Skip the wirelist header/format lines
        while i < len(lines):
            line = lines[i].rstrip()
            i += 1
            if 'FILNAM' in line:
                # Skip the 3 format description lines
                i += 3
                break
        
        # Parse page entries: lines starting with a filename (no tab)
        while i < len(lines):
            line = lines[i].rstrip()
            i += 1
            
            # Form feed = end of page list section
            if '\f' in line:
                break
            
            # Empty line
            if not line:
                continue
                
            # Tab-indented = metadata for previous page entry
            if line.startswith('\t'):
                parts = [p.strip() for p in line.split('\t') if p.strip()]
                # Filter out known board type fields
                parts = [p for p in parts if p not in ('DECPC', '8136-UG1', 'MULTIBUS')]
                text = ', '.join(parts)
                if pages and not title:
                    title = text.strip()
                elif pages and not subtitle:
                    subtitle = text.strip()
                continue
            
            # Page entry: starts with filename, tab-separated
            parts = line.split('\t')
            page_name = parts[0].strip()
            if page_name and len(page_name) < 20 and not page_name.startswith(' '):
                pages.append(page_name)
                # Extract date from first page entry
                if not date_str and len(parts) > 3:
                    date_str = parts[3].strip() if parts[3].strip() else ''
        
        if pages:
            results[wl_name] = {
                'pages': pages,
                'title': title,
                'subtitle': subtitle,
                'date': date_str,
            }
    
    return results


def _parse_drw_page(filepath: str) -> BoardPage | None:
    """Parse a single DRW file and return a BoardPage, or None on failure."""
    filename = os.path.basename(filepath)
    name = filename.replace('.drw.O', '')
    
    if name.lower() in EXCLUDED_FILES:
        return None
    
    try:
        parsed = parse_drw_file(filepath)
        trailer = getattr(parsed, 'trailer', None)
        
        title_1 = ''
        title_2 = ''
        page = ''
        page_of = ''
        
        if trailer:
            title_1 = getattr(trailer, 'title_line_1', '') or ''
            title_2 = getattr(trailer, 'title_line_2', '') or ''
            page = str(getattr(trailer, 'page', '') or '')
            page_of = str(getattr(trailer, 'of_string', '') or '')
        
        return BoardPage(
            name=name,
            filepath=filepath,
            page_num=page,
            page_of=page_of,
            title=title_1,
            subtitle=title_2,
            bodies=len(getattr(parsed, 'body_placements', [])),
            points=len(getattr(parsed, 'points', [])),
            body_defs=len(getattr(parsed, 'body_defs', []))
        )
    except Exception as e:
        logger.warning(f"Failed to parse {filepath}: {e}")
        return None


def _page_sort_key(pg: BoardPage):
    """Sort key for pages: numeric page number first, then alpha suffix."""
    m = re.match(r'^(\d+)', pg.page_num)
    if m:
        return (int(m.group(1)), pg.page_num)
    # Try extracting number from filename
    m = re.search(r'(\d+)', pg.name)
    if m:
        return (int(m.group(1)), pg.name)
    return (999, pg.page_num or pg.name)


def discover_boards(drw_dir: str, wl_dir: str | None = None) -> list[Board]:
    """Discover all boards using wirelist files as primary source.
    
    Args:
        drw_dir: Directory containing .drw.O files
        wl_dir: Directory containing .wl wirelist files. If None, looks for
                data/wirelists/ relative to drw_dir, or falls back to metadata-only.
    
    Returns:
        List of Board objects sorted by name, with pages sorted by page number.
    """
    # Resolve wirelist directory
    if wl_dir is None:
        # Try data/wirelists/ relative to project root
        project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
        candidate = os.path.join(project_root, 'data', 'wirelists')
        if os.path.isdir(candidate):
            wl_dir = candidate
    
    # Phase 1: Parse all DRW files
    all_pages = {}  # name -> BoardPage
    search_pattern = os.path.join(drw_dir, '*.drw.O')
    for filepath in glob.glob(search_pattern):
        page = _parse_drw_page(filepath)
        if page:
            all_pages[page.name.upper()] = page
    
    logger.info(f"Parsed {len(all_pages)} DRW files from {drw_dir}")
    
    # Phase 2: Parse wirelists for canonical board groupings
    wl_boards = {}
    claimed_pages = set()  # Track which pages are claimed by wirelists
    
    if wl_dir and os.path.isdir(wl_dir):
        wl_boards = _parse_wirelists(wl_dir)
        logger.info(f"Parsed {len(wl_boards)} wirelists from {wl_dir}")
    
    # Phase 3: Build boards from wirelists
    boards = []
    
    for wl_name, wl_data in sorted(wl_boards.items()):
        pages = []
        for page_name in wl_data['pages']:
            page_upper = page_name.upper()
            if page_upper in all_pages:
                pages.append(all_pages[page_upper])
                claimed_pages.add(page_upper)
        
        if not pages:
            continue
        
        # Sort pages by page number
        sorted_pages = sorted(pages, key=_page_sort_key)
        
        # Generate board name from wirelist metadata
        wl_title = wl_data.get('title', '').strip()
        # Clean up common title prefixes
        display_title = wl_title
        for prefix in ['PROPRIETARY SMI, ', '(C) 1982 SMI, ', '(C) 1983 SMI, ',
                       '(C) 1982 SMI. ', '(C) 1981 VSI. ', '(C) SUN-2 COLOR, ',
                       '(2) SUN-2 COLOR, ', 'SUN MICROSYSTEMS INC', 'SMI, ']:
            if display_title.upper().startswith(prefix):
                display_title = display_title[len(prefix):].strip()
                break
        
        # Also try page titles if wirelist title is generic
        if not display_title or display_title.startswith('501-'):
            # Use first page's trailer title
            for p in sorted_pages:
                if p.title.strip():
                    display_title = p.title.strip()
                    for prefix in ['PROPRIETARY SMI, ', '(C) 1982 SMI, ', '(C) 1983 SMI, ',
                                   '(C) 1982 SMI. ', '(C) SUN-2 COLOR, ', 'SMI, ']:
                        if display_title.upper().startswith(prefix):
                            display_title = display_title[len(prefix):].strip()
                            break
                    break
        
        board_name = f"{wl_name.upper()} — {display_title}" if display_title else wl_name.upper()
        
        board = Board(
            board_id=slugify(wl_name),
            name=board_name,
            pages=sorted_pages,
            source='wirelist',
            wirelist=wl_name
        )
        boards.append(board)
    
    # Phase 4: Group unclaimed pages by metadata (fallback)
    unclaimed = {name: page for name, page in all_pages.items() 
                 if name not in claimed_pages}
    
    if unclaimed:
        logger.info(f"{len(unclaimed)} pages not covered by wirelists, using metadata grouping")
        
        # Group by filename prefix (letters before digits)
        prefix_groups = defaultdict(list)
        for name, page in unclaimed.items():
            m = re.match(r'^([a-zA-Z]+)', page.name)
            if m:
                prefix = m.group(1).upper()
            else:
                prefix = page.name.upper()
            prefix_groups[prefix].append(page)
        
        for prefix, pages in sorted(prefix_groups.items()):
            sorted_pages = sorted(pages, key=_page_sort_key)
            
            # Get a title from the first page
            display_title = ''
            for p in sorted_pages:
                if p.title.strip():
                    display_title = p.title.strip()
                    for pfx in ['PROPRIETARY SMI, ', '(C) 1982 SMI, ', '(C) 1983 SMI, ',
                                '(C) SUN-2 COLOR, ', 'SUN MICROSYSTEMS INC', 'SMI, ']:
                        if display_title.upper().startswith(pfx):
                            display_title = display_title[len(pfx):].strip()
                            break
                    break
            
            board_name = f"{prefix} — {display_title}" if display_title else prefix
            board_id = slugify(prefix)
            
            # Ensure unique board_id
            seen_ids = {b.board_id for b in boards}
            if board_id in seen_ids:
                counter = 2
                while f"{board_id}_{counter}" in seen_ids:
                    counter += 1
                board_id = f"{board_id}_{counter}"
            
            board = Board(
                board_id=board_id,
                name=board_name,
                pages=sorted_pages,
                source='metadata'
            )
            boards.append(board)
    
    return sorted(boards, key=lambda b: b.name)
