"""Parser for SUDS PRT (parts list) files.

PRT files are text-based Bill of Materials generated by the SUDS
wirelister.  Each entry maps a DIP type to one or more component
locations (designators) on the PC board.

Format (tab-separated columns):
    PART NUMBER  DIPTYPE  COUNT  DESCRIPTION  LOCATIONS

Example lines:
    N/A      C        99                 C1-C86, C100-C112
             74S240*  4                  U3, U14, U40, U45
             68010    1                  U100

Locations can be individual (U3) or ranges (C1-C86, M100-M108).
Continuation lines have only the LOCATIONS field.
"""

from __future__ import annotations

import re
from pathlib import Path


def _expand_range(range_str: str) -> list[str]:
    """Expand 'U60-U62' → ['U60', 'U61', 'U62']. Passthrough for non-ranges."""
    m = re.match(r'^([A-Z]+)(\d+)-([A-Z]+)(\d+)$', range_str.strip())
    if not m:
        return [range_str.strip()]

    prefix1, start_s, prefix2, end_s = m.groups()
    if prefix1 != prefix2:
        return [range_str.strip()]

    start, end = int(start_s), int(end_s)
    if end < start or (end - start) > 1000:
        return [range_str.strip()]

    return [f'{prefix1}{i}' for i in range(start, end + 1)]


_LOCATION_PAT = re.compile(r'[A-Z]\d+(?:-[A-Z]\d+)?')


def _extract_locations(text: str) -> list[str]:
    """Extract and expand all location designators from a text field.

    Handles comma-separated lists with ranges:
      'U3, U14, U40, U45' → ['U3', 'U14', 'U40', 'U45']
      'C1-C86, C100-C112' → ['C1', ..., 'C86', 'C100', ..., 'C112']
    """
    result = []
    for item in text.split(','):
        item = item.strip()
        if item and _LOCATION_PAT.match(item):
            result.extend(_expand_range(item))
    return result


def parse_prt_file(path: str | Path) -> dict[str, str]:
    """Parse a PRT file and return a designator → dip_type mapping.

    Args:
        path: Path to the .prt file.

    Returns:
        Dict mapping designator strings (e.g. 'U100') to DIP type
        strings (e.g. '68010').
    """
    result: dict[str, str] = {}

    with open(str(path)) as f:
        content = f.read()

    in_parts = False
    current_diptype = ''

    for line in content.split('\n'):
        stripped = line.strip()
        if not stripped or stripped.startswith('\x0c'):
            # Reset on page breaks (form feed)
            continue

        # Detect the header row
        if 'DIPTYPE' in line and 'LOCATIONS' in line:
            in_parts = True
            continue

        if not in_parts:
            continue

        # Split on tabs
        fields = line.split('\t')

        # Find the DIP type: it's at tab position 2 (fields[2]) in the
        # standard PRT format. Check if field 2 is a non-empty type name
        # and field 4 is a numeric count.
        if len(fields) > 4 and fields[2].strip():
            candidate = fields[2].strip()
            count_field = fields[4].strip() if len(fields) > 4 else ''
            if count_field.isdigit():
                current_diptype = candidate.rstrip('\\')

        # Extract locations from the last populated field(s)
        # Locations appear in various tab positions (9 or 10 typically)
        if current_diptype:
            for f in fields:
                f = f.strip()
                if not f:
                    continue
                locs = _extract_locations(f)
                if locs:
                    for desig in locs:
                        result[desig] = current_diptype

    return result
