"""STF (Stuffing File) parser for SUDS PCB component designators.

The STF file maps board body positions to component designators and
DIP type names.  It is generated by the SUDS schematic editor and
consumed by the silkscreen generator (pcdvi.sai / pcpgrb.sai).

Format
------
The STF file is a tab-delimited text file with:
  - A header section listing schematic sheets
  - A data section after a form-feed (0x0C) with columns:
      PART NUMBER  DIPTYPE  LOC  BODY  FILE  POS

The LOC column contains component designators followed by "( )"
(e.g., "U4( )", "C3( )", "001-047( )").  The next field after
the "( )" entry is the BODY/DIP type name (e.g., "74LS374", "C").

Matching
--------
STF entries match PC file bodies by **file order**: the N-th body
in the PC file corresponds to the N-th STF entry.  This was verified
on g.pc.O/g.stf (215=215) and qx.pc.O/qx.stf (174=174).
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path


@dataclass
class STFEntry:
    """One component entry from the STF file."""
    designator: str = ""       # Component designator (e.g., "U4", "C3", "001-047")
    dip_type: str = ""         # DIP body type name (e.g., "74LS374", "C", "R")
    raw_field: str = ""        # Original field including "( )" suffix


@dataclass
class STFFile:
    """Parsed stuffing file.

    Entries are matched to PC bodies by **component designator**:
    the body's L/N fields are decoded through SUDS_DECALPH (1-based)
    to produce a string like 'U704', which is looked up in the STF's
    LOC column.
    """
    entries: list[STFEntry] = field(default_factory=list)
    source_path: str = ""
    _desig_index: dict[str, STFEntry] = field(
        default_factory=dict, init=False, repr=False)

    def __post_init__(self) -> None:
        """Build lookup index by designator."""
        self._desig_index = {}
        for entry in self.entries:
            if entry.designator:
                self._desig_index[entry.designator] = entry

    def type_for_designator(self, designator: str) -> str | None:
        """Look up the DIP type name (e.g., '74LS374') for a designator.

        This matches the pcdvi.sai silkscreen lookup at line 1281:
          if equ(loc, stfloc[i]) then name ← stfname[i]

        Args:
            designator: Component designator string (e.g., 'U704', 'C3').

        Returns:
            DIP type name if found, None otherwise.
        """
        entry = self._desig_index.get(designator)
        if entry:
            return entry.dip_type.rstrip('\\')
        return None

    def designator_for_body_index(self, idx: int) -> str | None:
        """Get the component designator for the N-th body (0-indexed).

        Returns None if the index is out of range.
        """
        if 0 <= idx < len(self.entries):
            return self.entries[idx].designator
        return None

    def dip_type_for_body_index(self, idx: int) -> str | None:
        """Get the DIP type name for the N-th body (0-indexed).

        Returns None if the index is out of range.
        """
        if 0 <= idx < len(self.entries):
            return self.entries[idx].dip_type
        return None


def parse_stf_file(path: str | Path) -> STFFile:
    """Parse an STF stuffing file.

    Mimics the pcdvi.sai silkscreen reader (lines 1229-1241):
      - Splits on tab and newline
      - Looks for fields ending with "( )"
      - Strips the suffix to get the designator
      - Takes the next field as the DIP type name

    Args:
        path: Path to the STF file.

    Returns:
        Parsed STFFile with entries in file order.
    """
    path = Path(path)
    content = path.read_text(encoding='ascii', errors='replace')

    # Split on tabs and line endings (matching SAIL's setbreak on TAB, CR)
    fields = re.split(r'[\t\r\n]+', content)

    entries: list[STFEntry] = []
    i = 0
    while i < len(fields):
        f = fields[i]
        if f.endswith('( )') and i + 1 < len(fields):
            designator = f[:-3].strip()   # Strip "( )" suffix
            dip_type = fields[i + 1].strip()
            entries.append(STFEntry(
                designator=designator,
                dip_type=dip_type,
                raw_field=f,
            ))
            i += 2  # Skip the DIP type field
        else:
            i += 1

    return STFFile(entries=entries, source_path=str(path))
